### ISSUE TITLE
Esse seu projeto "Usando-DPC" não está funcionando.

### ISSUE THREAD

**Issue by nilton10051997** [GabrielCoutz/Usando-DPC#1]
O problema do chiado no áudio utilizando o Razer Surround com esse seu projeto "Usando-DPC" não está funcionando.
Fiz exatamente o procedimento com todos os passos.
No começo, após clicar em "Começar" na janela do programa aberto, o problema não tinha sido resolvido, nem mesmo depois de terminado e de fechada a janela.
Então concluí que o problema poderia ser resolvido fazendo o procedimento para o programa iniciar com o Windows e reiniciando ele.
Fiz todos os procedimentos exatamente como no tutorial, reiniciei o computador algumas vezes e em nenhuma ele foi corrigido. Não é corrigido nem abrindo manualmente o programa. Claro, tudo executando como administrador.
Vale lembrar que sou da área de TI e que o problema se resolve com o método do BlueStacks perfeitamente, porém tem o ponto negativo dele consumir alguma memória RAM e ter que abrir e fazer o procedimento toda vez que o computador é reiniciado.
Fico no aguardo para caso consiga solucionar esse problema de alguma forma.
Obrigado pela ajuda desde já.
Bons estudos.

**Comment by GabrielCoutz** [comment]
@nilton10051997 Boa dia, a alguns dias verifiquei o mesmo problema, até deixei o projeto todo em estado de 'manutenção' para ser resolvido. Após esses testes, o problema foi (ou pelo menos eu achei) resolvido então voltei tudo ao ar.
Agradeço o feedback e vou ver oq está acontecendo, até lá, peço desculpas pelo inconveniente ;-; .

**Comment by GabrielCoutz** [comment]
@nilton10051997 Fiz algumas alterações junto com implementações, e gostaria q vc fosse o primeiro a testar. 

Por favor, faça o download **[aqui](https://github.com/GabrielCoutz/Usando-DPC/archive/refs/heads/main.zip)** e apenas execute uma única vez _(sem ser como administrador)_, depois pode reiniciar o pc.

Aguardo seu retorno.
