### ISSUE TITLE
Programa tirar chiado do Razer surround

### ISSUE THREAD

**Issue by Sabathan666** [GabrielCoutz/Usando-DPC#3]
Bom dia Gabriel eu estava usando o seu programa que voce criou pra tirar o chiado do razer surround porem agora nao estou mais precisando pelo fato de ter comprado o Dolby Vision e nao vou mais usar o Razer,ai eu queria saber como faço pra desinstalar o programa e que que nao fique mais abrindo o CMD sempre que ligar o PC?

**Comment by GabrielCoutz** [comment]
Boa tar @Sabathan666, basta dar um **```WINDOWS + R```** e colar esse caminho:

**```%AppData%\Microsoft\Windows\Start Menu\Programs\Startup```**

Depois é só apagar o arquivo **```Iniciador.exe```**.

Aguardo seu retorno para saber se deu certo.

**Comment by Sabathan666** [comment]
boa tarde,eu resolvi dessa forma mesmo procurei pelos arquivos executaveis
e exclui eles tanto o iniciador como o DP latency,mas agradeço pela atenção
muito obrigado!!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em ter., 17 de mai. de 2022 às 15:22, Gabriel Coutinho Cassiano <
***@***.***> escreveu:
