### ISSUE TITLE
Amigo... instalei, mas quando seleciono o razer surround fica sem som nenhum o computador...

### ISSUE THREAD

**Issue by GuigoBR** [GabrielCoutz/Usando-DPC#5]
Amigo... instalei, mas quando seleciono o razer surround fica sem som nenhum o computador...

e agradecer acima de tudo!!!!! ainda mais a se prontificar a ser contactado!!!

**Comment by GabrielCoutz** [comment]
Bom dia @GuigoBR, obrigado eu por entrar em contato kk. Tente seguir esses passos para ver se o som volta:

Abra o **Razer Surround** e vá em **Configurações**.

Existe duas opções: '**LIGAR**' e '**DESLIGAR**', tente mudar de uma para a outra, desligue e ligue.
Me fale se isso funcionou =).

Fico no aguardo da sua resposta.

**Comment by GuigoBR** [comment]
> Bom dia @GuigoBR, obrigado eu por entrar em contato kk. Tente seguir esses passos para ver se o som volta:
> 
> Abra o **Razer Surround** e vá em **Configurações**.
> 
> Existe duas opções: '**LIGAR**' e '**DESLIGAR**', tente mudar de uma para a outra, desligue e ligue. Me fale se isso funcionou =).
> 
> Fico no aguardo da sua resposta.

Então amigo... isso é o basico, inclusive mudo para o alto falante normal e o som funciona, coloco para o do razor e fica mudo... tentei de tudo que é jeito... ate já sai apagando os arquivos que cria, tentar instalar manualmente, não sei, porque abre o cmd tao rapido que não mostra nada e já fecha e ai fica mudo e talz...

**Comment by GabrielCoutz** [comment]
Boa tarde @GuigoBR, tente seguir essas etapas para ver se identificamos onde está o problema:

### 1° Tentativa

Feche tanto os arquivos criados pelo meu programa, quando o Razer Surround.

Inicie o Razer Surround como **administrador**. E veja se o som volta.

Em seguida, rode o programa. Note se o som funciona.

<hr>

### 2° Tentativa

Com o Razer Surround aberto, vá até seus **Documentos** e execute o programa **dpclat.exe**. Perceba se o som está saindo.

Se não, aperte **CTRL + SHIFT + ESC**, vá até **Detalhes** e finalize o processo **dpclat.exe**. Depois tente executá-lo novamente mas agora como **administrador**. O áudio voltou ao normal?.

Aguardo seu retorno.

**Comment by GuigoBR** [comment]
E aew amigo, nenhuma das duas opções, serviu... se quiser posso colocar o anydesk aqui para tu ver se quiser...

**Comment by GabrielCoutz** [comment]
Bom dia @GuigoBR, acredito que a versão 62bits não influencia no funcionamento do Razer Surround. Fico triste de saber que não foi possível resolver seu problema ;-;, pode me dizer se o chiado ainda existe ou se continua?

**Comment by GuigoBR** [comment]
Na verdade, quando seleciono o Razer, simplesmente não há nenhum som, logo, sem chiado, mas... kkkkk

**Comment by GabrielCoutz** [comment]
Boa noite @GuigoBR, desculpe a demora para responder. Infelizmente não tenho ideia de mais o que posso fazer para te ajudar, aconselharia tentar reinstalar o Razer Surround para ver se volta a funcionar. Sinto muito não conseguir resolver seu problema ;-
