### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by GabrielMateus** [GabrielCoutz/Usando-DPC#6]
Boa noite mano, é o seguinte ainda utilizo o seu programa (que por sinal é muito bom) só que o seguinte, a forma que eu estou usando pra quando inicia o Windows é diferente mas funcional, eu só queria retirar a tela de agradecimento do final quando o aplicativo termina de funcionar manja, por que do método padrão que vc ensina não funcionou no meu pc, espero que entenda, desde já Obrigado. Segue a print da tela que estou falando.
![image](https://user-images.githubusercontent.com/56881385/210192108-d85c0040-1f3d-4cce-a6c8-9067723aa502.png)

**Comment by GabrielCoutz** [comment]
Bom dia meu querido, fico feliz que gostou da minha solução e que possui uma versão diferente, e sinto muito por não ter funcionado no seu pc ;-;

Este programa q desenvolvi foi escrito em Python a muito tempo atrás, hoje estou na área de Front-end, que obviamente, utiliza linguagens totalmente diferentes de Python.

Então, por motivos de estudos, não possuo disponibilidade para alterações no código (e tbm prq esqueci quase tudo KKKK).

Logo, decidi deixar o código fonte disponível para download junto com os arquivos já existentes, espero que te ajude em algo.
Qualquer dúvida a mais, fico à disposição ^^
