### ISSUE TITLE
Não inicializa junto com Windows

### ISSUE THREAD

**Issue by Erick-AS** [GabrielCoutz/Usando-DPC#7]
Fala Gabriel, boa noite!

Então comecei a usar o DPC antes eu utilizava o bluestarcks agora estou com o DPC mas ele não inicia junto com o Win, toda vez preciso acionar ele e sempre aparece um erro e some rapidamente e o problema do chiado para. Existe algo que eu possa fazer para que ele inicie junto com Win ?

**Comment by GabrielCoutz** [comment]
E aí Erick, tranquilo?

Fico triste em saber que o programa não está mais funcionando do jeito esperado ;-
Infelizmente não estou mais mexendo com este projeto, então o código se encontra desatualizado e como pode perceber, com problemas. Por conta de tempo e não dominar mais Python, linguagem utilizada, como antes, não consigo entender direito o que fiz XD, logo não posso ajudar muito =,(

Deixei o código fonte disponível nas pastas de download, fique à vontade para dar uma lida e tentar entender o algoritmo e alterá-lo conforme necessário.

Peço desculpas novamente.
